apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fx1btdpjg-go 
  janus-idp.io/tekton: fx1btdpjg-go
  backstage.io/kubernetes-id: fx1btdpjg-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fx1btdpjg-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml